<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TestSomething" Id="{a5ea8811-5301-4f6c-aafd-b2e96e83b4a4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestSomething EXTENDS FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestTrue();]]></ST>
    </Implementation>
    <Method Name="TestTrue" Id="{5dcda336-eb7c-4bc2-a049-4f178c78790e}">
      <Declaration><![CDATA[METHOD TestTrue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('TestAdd');

AssertTrue(TRUE, 'Condition is not true');

TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>