<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TestSuite2" Id="{3a6274d6-6083-4f38-89f5-174a468b61d8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestSuite2 EXTENDS FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestCase2A();
TestCase2B();

TEST('TestCase2C');

AssertTrue(TRUE, 'Condition is not true');
AssertTrue(FALSE, 'Condition is not true');

TEST_FINISHED();]]></ST>
    </Implementation>
    <Method Name="Method_CFC" Id="{6220ef8c-b93c-4d03-82f1-d0fb0e0f8f17}">
      <Declaration><![CDATA[METHOD PUBLIC Method_CFC : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList" />
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" />
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">0</v>
                <v n="CanvasHeight">0</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="Int32">System.Int32</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Method>
    <Method Name="Method_FBD" Id="{89216776-ec63-4446-89c7-6f879b632364}">
      <Declaration><![CDATA[METHOD PUBLIC Method_FBD : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">5L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="Method_LD" Id="{ed18b6ba-a455-4ed5-ba73-d77ee2c19325}">
      <Declaration><![CDATA[METHOD PUBLIC Method_LD : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Ld"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">5L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="Method_UML" Id="{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}">
      <Declaration><![CDATA[METHOD PUBLIC Method_UML : REFERENCE TO FB_Test
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <StateChart>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="UMLStateChart">
                <v n="Abortable">true</v>
                <v n="UseVarInstForMethods">true</v>
                <v n="StatesCount">5</v>
                <v n="HistoryCount">0</v>
                <v n="TransitionsCount">5</v>
                <v n="RegionsCount">0</v>
                <v n="TracesCount">0</v>
                <v n="StatesInitString">":=[(ID := 1, Name := 'GeneratedStartStateForAbort1', StateType := _UML_SC_StateTypes.InitialState, StartOfTransitionIndex := 1, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 2, Name := 'GeneratedFinalStateForAbort1', StateType := _UML_SC_StateTypes.FinalState, StartOfTransitionIndex := 0, OutGoingTransitionsCount := 0, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 3, Name := 'State1', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 2, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 4, Name := 'StartState1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 4, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 5, Name := 'EndState1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 5, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) ];
"</v>
                <v n="TransitionsInitString">":=[(ID := 1, StartStateID := 1, EndStateID := 4, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 2, StartStateID := 3, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 3, StartStateID := 3, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 4, StartStateID := 4, EndStateID := 3, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 5, StartStateID := 5, EndStateID := 2, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False)];
"</v>
                <v n="RegionsInitString">""</v>
                <v n="StateNamesString">"GeneratedStartStateForAbort1:INT:=1;
GeneratedFinalStateForAbort1:INT:=2;
State1:INT:=3;
StartState1:INT:=4;
EndState1:INT:=5;
"</v>
                <n n="StateNamesInitString" />
                <v n="ForceActionRemove">false</v>
                <d n="RegionsWithStartStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                  <v>00000000-0000-0000-0000-000000000000</v>
                  <v>1</v>
                </d>
                <d n="RegionsWithHistoryStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                  <v>00000000-0000-0000-0000-000000000000</v>
                  <v>1</v>
                </d>
                <d n="RegionsWithEndStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                  <v>00000000-0000-0000-0000-000000000000</v>
                  <v>1</v>
                </d>
                <n n="BreakPointGuids" />
                <v n="UmlEditorRestrictions" t="EditorRestrictions">None</v>
                <v n="DUTObjectGuid">{5fd6deb3-2f08-4dc4-8d2b-0cf1d94dd109}</v>
                <v n="DUTNamesObjectGuid">{dd8c4d1c-6626-48a8-aee9-d05d1e2c929f}</v>
                <v n="TraceObject">{00000000-0000-0000-0000-000000000000}</v>
                <v n="IsCompiling">false</v>
                <v n="HideLanguageModel">false</v>
                <v n="DefaultStateSizeX">62</v>
                <v n="DefaultStateSizeY">32</v>
                <v n="SuppressAutomaticLibraryLoading">false</v>
                <v n="DiagramName">"Method_UML"</v>
                <v n="DiagramGuid">{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}</v>
                <v n="IsActionRemoving">false</v>
                <v n="ForceRepaintDiagram">false</v>
                <v n="Documentationdiagram">false</v>
                <v n="ApplicationGuidForDiagram">{00000000-0000-0000-0000-000000000000}</v>
                <v n="AutomaticLayOutHeightSpace">0</v>
                <v n="AutomaticLayOutWidthSpace">0</v>
                <d n="ElementObjects" t="Hashtable" ckt="Guid">
                  <v>27943c4e-de77-4fd5-905f-c6e7bc0b05c3</v>
                  <o t="UMLStateChartElement">
                    <v n="StateChartGuid">{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}</v>
                    <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                    <v n="EntryLocalVariableName">""</v>
                    <v n="EntryActionName">""</v>
                    <v n="EntryParametersString">""</v>
                    <v n="EntryActionText">""</v>
                    <v n="InjectedDoImplementationCode">""</v>
                    <v n="DoActionText">""</v>
                    <v n="ExitActionText">""</v>
                    <v n="DoLocalVariableName">""</v>
                    <v n="DoActionName">""</v>
                    <v n="DoParametersString">""</v>
                    <v n="ExitLocalVariableName">""</v>
                    <v n="ExitActionName">""</v>
                    <v n="ExitParametersString">""</v>
                    <v n="HasEntryAction">false</v>
                    <v n="HasDoAction">false</v>
                    <v n="HasExitAction">false</v>
                    <v n="PropertyID">0</v>
                    <v n="wasFork">false</v>
                    <d n="ActionList" t="Hashtable" />
                    <d n="PropertyList" t="Hashtable" />
                    <v n="ElementName">"State1"</v>
                    <v n="MethodID">0</v>
                    <d n="MethodStereotypContainer" t="Hashtable" />
                    <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                      <v n="ShowAttributes">true</v>
                      <v n="ShowMethods">true</v>
                      <v n="RepresentedElement">1</v>
                      <v n="IsElementVisible">true</v>
                      <v n="TopPosition">220</v>
                      <v n="LeftPosition">250</v>
                      <v n="WidthValue">62</v>
                      <v n="MinWidthValue">0</v>
                      <v n="Height">32</v>
                      <v n="MinHeight">0</v>
                      <v n="AutomaticLayout">false</v>
                      <d n="DockingPoints" t="Hashtable" />
                    </o>
                    <l2 n="VariableList" />
                    <n n="StereotypeContainer" />
                    <v n="HasGraphicalRepresentation">true</v>
                    <v n="bIsVisualisationChanged">false</v>
                    <v n="IsType" t="UMLType">UMLStateChartElement</v>
                    <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                    <v n="DefaultCellSizeX">62</v>
                    <v n="DefaultCellSizeY">32</v>
                    <v n="IsDocumentation">false</v>
                    <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="ParsedMethods">false</v>
                    <v n="ParsedProperties">false</v>
                    <v n="GeneratorId">0</v>
                    <v n="UserDefined">true</v>
                    <v n="ElementID">1</v>
                    <v n="ElementObjectGuid">{27943c4e-de77-4fd5-905f-c6e7bc0b05c3}</v>
                    <v n="ParentGuid">{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}</v>
                    <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="ShowedStereotype">{dd45b7ff-a8ee-4f24-a2fb-a2557b725aaf}</v>
                    <v n="ReplacewithImage">false</v>
                    <v n="AutomaticLayout">false</v>
                    <v n="PositionCounter">1L</v>
                    <v n="UMLPosition">-1L</v>
                    <v n="IsModified">false</v>
                    <v n="ARGBElementColor">-13447886</v>
                    <v n="ZOrder">5U</v>
                  </o>
                  <v>7c75664d-1068-4216-bb68-0988792aad57</v>
                  <o t="UMLStateChartPseudoElement">
                    <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                      <v n="ShowAttributes">true</v>
                      <v n="ShowMethods">true</v>
                      <v n="RepresentedElement">1</v>
                      <v n="IsElementVisible">true</v>
                      <v n="TopPosition">158</v>
                      <v n="LeftPosition">236</v>
                      <v n="WidthValue">20</v>
                      <v n="MinWidthValue">0</v>
                      <v n="Height">20</v>
                      <v n="MinHeight">0</v>
                      <v n="AutomaticLayout">false</v>
                      <d n="DockingPoints" t="Hashtable" />
                    </o>
                    <v n="Condition">""</v>
                    <v n="HistoryType" t="HistoryTypes">None</v>
                    <v n="StateChartGuid">{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}</v>
                    <v n="EntryLocalVariableName">""</v>
                    <v n="EntryActionName">""</v>
                    <v n="EntryParametersString">""</v>
                    <v n="EntryActionText">""</v>
                    <v n="InjectedDoImplementationCode">""</v>
                    <v n="DoActionText">""</v>
                    <v n="ExitActionText">""</v>
                    <v n="DoLocalVariableName">""</v>
                    <v n="DoActionName">""</v>
                    <v n="DoParametersString">""</v>
                    <v n="ExitLocalVariableName">""</v>
                    <v n="ExitActionName">""</v>
                    <v n="ExitParametersString">""</v>
                    <v n="HasEntryAction">false</v>
                    <v n="HasDoAction">false</v>
                    <v n="HasExitAction">false</v>
                    <v n="PropertyID">0</v>
                    <v n="wasFork">false</v>
                    <d n="ActionList" t="Hashtable" />
                    <d n="PropertyList" t="Hashtable" />
                    <v n="ElementName">"StartState1"</v>
                    <v n="MethodID">0</v>
                    <d n="MethodStereotypContainer" t="Hashtable" />
                    <l2 n="VariableList" />
                    <n n="StereotypeContainer" />
                    <v n="HasGraphicalRepresentation">true</v>
                    <v n="bIsVisualisationChanged">false</v>
                    <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                    <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                    <v n="DefaultCellSizeX">20</v>
                    <v n="DefaultCellSizeY">20</v>
                    <v n="IsDocumentation">false</v>
                    <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="ParsedMethods">false</v>
                    <v n="ParsedProperties">false</v>
                    <v n="GeneratorId">0</v>
                    <v n="UserDefined">true</v>
                    <v n="ElementID">1</v>
                    <v n="ElementObjectGuid">{7c75664d-1068-4216-bb68-0988792aad57}</v>
                    <v n="ParentGuid">{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}</v>
                    <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="ShowedStereotype">{ceee2a2d-9756-4396-be18-2e9ecb9460a9}</v>
                    <v n="ReplacewithImage">false</v>
                    <v n="AutomaticLayout">false</v>
                    <v n="PositionCounter">1L</v>
                    <v n="UMLPosition">-1L</v>
                    <v n="IsModified">false</v>
                    <v n="ARGBElementColor">0</v>
                    <v n="ZOrder">1U</v>
                  </o>
                  <v>bfa2c643-82d0-4726-86c3-cf47d8f6028d</v>
                  <o t="UMLStateChartPseudoElement">
                    <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                      <v n="ShowAttributes">true</v>
                      <v n="ShowMethods">true</v>
                      <v n="RepresentedElement">1</v>
                      <v n="IsElementVisible">true</v>
                      <v n="TopPosition">278</v>
                      <v n="LeftPosition">222</v>
                      <v n="WidthValue">20</v>
                      <v n="MinWidthValue">0</v>
                      <v n="Height">20</v>
                      <v n="MinHeight">0</v>
                      <v n="AutomaticLayout">false</v>
                      <d n="DockingPoints" t="Hashtable" />
                    </o>
                    <v n="Condition">""</v>
                    <v n="HistoryType" t="HistoryTypes">None</v>
                    <v n="StateChartGuid">{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}</v>
                    <v n="EntryLocalVariableName">""</v>
                    <v n="EntryActionName">""</v>
                    <v n="EntryParametersString">""</v>
                    <v n="EntryActionText">""</v>
                    <v n="InjectedDoImplementationCode">""</v>
                    <v n="DoActionText">""</v>
                    <v n="ExitActionText">""</v>
                    <v n="DoLocalVariableName">""</v>
                    <v n="DoActionName">""</v>
                    <v n="DoParametersString">""</v>
                    <v n="ExitLocalVariableName">""</v>
                    <v n="ExitActionName">""</v>
                    <v n="ExitParametersString">""</v>
                    <v n="HasEntryAction">false</v>
                    <v n="HasDoAction">false</v>
                    <v n="HasExitAction">false</v>
                    <v n="PropertyID">0</v>
                    <v n="wasFork">false</v>
                    <d n="ActionList" t="Hashtable" />
                    <d n="PropertyList" t="Hashtable" />
                    <v n="ElementName">"EndState1"</v>
                    <v n="MethodID">0</v>
                    <d n="MethodStereotypContainer" t="Hashtable" />
                    <l2 n="VariableList" />
                    <n n="StereotypeContainer" />
                    <v n="HasGraphicalRepresentation">true</v>
                    <v n="bIsVisualisationChanged">false</v>
                    <v n="IsType" t="UMLType">UMLStateChartEndState</v>
                    <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                    <v n="DefaultCellSizeX">20</v>
                    <v n="DefaultCellSizeY">20</v>
                    <v n="IsDocumentation">false</v>
                    <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="ParsedMethods">false</v>
                    <v n="ParsedProperties">false</v>
                    <v n="GeneratorId">0</v>
                    <v n="UserDefined">true</v>
                    <v n="ElementID">1</v>
                    <v n="ElementObjectGuid">{bfa2c643-82d0-4726-86c3-cf47d8f6028d}</v>
                    <v n="ParentGuid">{75329e18-c2b7-42f7-9e4e-69f84cf1fe42}</v>
                    <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="ShowedStereotype">{25c0e042-6f2b-4d7c-a63e-4947b40690c7}</v>
                    <v n="ReplacewithImage">false</v>
                    <v n="AutomaticLayout">false</v>
                    <v n="PositionCounter">1L</v>
                    <v n="UMLPosition">-1L</v>
                    <v n="IsModified">false</v>
                    <v n="ARGBElementColor">0</v>
                    <v n="ZOrder">2U</v>
                  </o>
                </d>
                <v n="FirstPaint">true</v>
                <v n="NextElementID">0</v>
                <d n="UMLRelationObjects" t="Hashtable" ckt="Guid" cvt="UMLRelation">
                  <v>bd255ad8-73c8-46b4-a11e-4c77f6294430</v>
                  <o>
                    <v n="HasGraphicalRepresentation">true</v>
                    <v n="StartUMLElement">{7c75664d-1068-4216-bb68-0988792aad57}</v>
                    <v n="HighlightedLine">false</v>
                    <v n="ZOrder">0U</v>
                    <v n="SpecialHandling">false</v>
                    <v n="ActionLocalVariableName">""</v>
                    <v n="ActionParametersString">""</v>
                    <n n="ActionName" />
                    <v n="ActionText">""</v>
                    <v n="InjectedActionCode">""</v>
                    <v n="InjectedActionCodeBefore">true</v>
                    <v n="ActionTextLength">100</v>
                    <v n="ConditionText">""</v>
                    <v n="LengthConditionText">100</v>
                    <v n="RelationID">2</v>
                    <v n="TriggerlessStatechartTransition">true</v>
                    <v n="EndUMLElement">{27943c4e-de77-4fd5-905f-c6e7bc0b05c3}</v>
                    <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                      <v n="RelationID">{bd255ad8-73c8-46b4-a11e-4c77f6294430}</v>
                      <v n="FlagPosition" t="Double">0.5</v>
                      <d n="flagsX" t="Hashtable" />
                      <d n="flagsY" t="Hashtable" />
                      <o n="StartAnchor" t="UMLAnchorPoint">
                        <v n="AnchorID">0</v>
                        <v n="AnchorLeftPosition">251</v>
                        <v n="AnchorTopPosition">163</v>
                        <v n="AnchorRelationID">{bd255ad8-73c8-46b4-a11e-4c77f6294430}</v>
                        <v n="StartAnchor">true</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">Right</v>
                      </o>
                      <o n="EndAnchor" t="UMLAnchorPoint">
                        <v n="AnchorID">2</v>
                        <v n="AnchorLeftPosition">277</v>
                        <v n="AnchorTopPosition">215</v>
                        <v n="AnchorRelationID">{bd255ad8-73c8-46b4-a11e-4c77f6294430}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">true</v>
                        <v n="AnchorDockedState" t="Docked">Bottom</v>
                      </o>
                      <v n="NextAnchorID">2</v>
                      <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                        <v>1</v>
                        <o>
                          <v n="AnchorID">1</v>
                          <v n="AnchorLeftPosition">277</v>
                          <v n="AnchorTopPosition">163</v>
                          <v n="AnchorRelationID">{bd255ad8-73c8-46b4-a11e-4c77f6294430}</v>
                          <v n="StartAnchor">false</v>
                          <v n="EndAnchor">false</v>
                          <v n="AnchorDockedState" t="Docked">NotDocked</v>
                        </o>
                      </d>
                      <v n="RelationIsLinear">false</v>
                      <v n="RelationIsFreeHand">false</v>
                    </o>
                    <v n="ReferenceGuid">{bd255ad8-73c8-46b4-a11e-4c77f6294430}</v>
                    <v n="RelationGuid">{bd255ad8-73c8-46b4-a11e-4c77f6294430}</v>
                    <v n="RelationName">""</v>
                    <n n="RelationStereotypes" />
                    <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                    <v n="IsReferenceTo">false</v>
                    <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                    <v n="Priority">1</v>
                    <v n="GeneratesCode">false</v>
                    <v n="StartElementShowArrow">false</v>
                    <v n="StartElementCardnality">""</v>
                    <v n="EndElementCardnality">""</v>
                    <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                    <v n="EndElementShowArrow">true</v>
                    <v n="StartElementRoleName">""</v>
                    <v n="EndElementRoleName">""</v>
                    <v n="UserCreated">true</v>
                    <v n="GeneratedByCode">false</v>
                    <v n="AllowRoutingOptimisation">true</v>
                    <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                      <v>Priority</v>
                      <v>1</v>
                    </d>
                    <v n="Position">-1L</v>
                    <v n="PositionCounter">1L</v>
                    <v n="IsModified">false</v>
                    <v n="ARGBElementColor">0</v>
                  </o>
                  <v>c7c0963f-5ae5-4645-98f1-f8436613952a</v>
                  <o>
                    <v n="HasGraphicalRepresentation">true</v>
                    <v n="StartUMLElement">{27943c4e-de77-4fd5-905f-c6e7bc0b05c3}</v>
                    <v n="HighlightedLine">false</v>
                    <v n="ZOrder">5U</v>
                    <v n="SpecialHandling">false</v>
                    <v n="ActionLocalVariableName">""</v>
                    <v n="ActionParametersString">""</v>
                    <n n="ActionName" />
                    <v n="ActionText">""</v>
                    <v n="InjectedActionCode">""</v>
                    <v n="InjectedActionCodeBefore">true</v>
                    <v n="ActionTextLength">100</v>
                    <v n="ConditionText">"TRUE"</v>
                    <v n="LengthConditionText">100</v>
                    <v n="RelationID">1</v>
                    <v n="TriggerlessStatechartTransition">true</v>
                    <v n="EndUMLElement">{bfa2c643-82d0-4726-86c3-cf47d8f6028d}</v>
                    <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                      <v n="RelationID">{c7c0963f-5ae5-4645-98f1-f8436613952a}</v>
                      <v n="FlagPosition" t="Double">0.5</v>
                      <d n="flagsX" t="Hashtable" />
                      <d n="flagsY" t="Hashtable" />
                      <o n="StartAnchor" t="UMLAnchorPoint">
                        <v n="AnchorID">0</v>
                        <v n="AnchorLeftPosition">276</v>
                        <v n="AnchorTopPosition">247</v>
                        <v n="AnchorRelationID">{c7c0963f-5ae5-4645-98f1-f8436613952a}</v>
                        <v n="StartAnchor">true</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                      <o n="EndAnchor" t="UMLAnchorPoint">
                        <v n="AnchorID">2</v>
                        <v n="AnchorLeftPosition">237</v>
                        <v n="AnchorTopPosition">282</v>
                        <v n="AnchorRelationID">{c7c0963f-5ae5-4645-98f1-f8436613952a}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">true</v>
                        <v n="AnchorDockedState" t="Docked">Left</v>
                      </o>
                      <v n="NextAnchorID">2</v>
                      <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                        <v>1</v>
                        <o>
                          <v n="AnchorID">1</v>
                          <v n="AnchorLeftPosition">276</v>
                          <v n="AnchorTopPosition">282</v>
                          <v n="AnchorRelationID">{c7c0963f-5ae5-4645-98f1-f8436613952a}</v>
                          <v n="StartAnchor">false</v>
                          <v n="EndAnchor">false</v>
                          <v n="AnchorDockedState" t="Docked">NotDocked</v>
                        </o>
                      </d>
                      <v n="RelationIsLinear">false</v>
                      <v n="RelationIsFreeHand">false</v>
                    </o>
                    <v n="ReferenceGuid">{c7c0963f-5ae5-4645-98f1-f8436613952a}</v>
                    <v n="RelationGuid">{c7c0963f-5ae5-4645-98f1-f8436613952a}</v>
                    <v n="RelationName">""</v>
                    <n n="RelationStereotypes" />
                    <v n="RelationType" t="RelationTypes">Transition</v>
                    <v n="IsReferenceTo">false</v>
                    <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                    <v n="Priority">1</v>
                    <v n="GeneratesCode">false</v>
                    <v n="StartElementShowArrow">false</v>
                    <v n="StartElementCardnality">""</v>
                    <v n="EndElementCardnality">""</v>
                    <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                    <v n="EndElementShowArrow">true</v>
                    <v n="StartElementRoleName">""</v>
                    <v n="EndElementRoleName">""</v>
                    <v n="UserCreated">true</v>
                    <v n="GeneratedByCode">false</v>
                    <v n="AllowRoutingOptimisation">true</v>
                    <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                      <v>Priority</v>
                      <v>1</v>
                    </d>
                    <v n="Position">-1L</v>
                    <v n="PositionCounter">1L</v>
                    <v n="IsModified">false</v>
                    <v n="ARGBElementColor">0</v>
                  </o>
                </d>
                <v n="NextRelationID">0</v>
                <v n="DefaultAutomaticLayout">false</v>
                <o n="ClassDiagrammProperties" t="UMLDiagramProperties">
                  <v n="ArrayOfPointerToClassPresentation" t="RelationTypes">Empty</v>
                  <v n="ArrayOfClassPresentation" t="RelationTypes">Empty</v>
                  <v n="ArrayOfInterfacePresentation" t="RelationTypes">Empty</v>
                  <v n="ArrayOfInterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                  <v n="PointerToClassPresentation" t="RelationTypes">Empty</v>
                  <v n="ClassPresentation" t="RelationTypes">Empty</v>
                  <v n="InterfacePresentation" t="RelationTypes">Empty</v>
                  <v n="InterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                  <v n="ShowRoleNames">true</v>
                  <v n="ShowCardinalities">true</v>
                  <v n="ShowRelationNames">true</v>
                  <v n="ShowAttributesinClasses">false</v>
                  <v n="ShowMethodsInClasses">false</v>
                  <v n="ParametersMaximumLength">20</v>
                </o>
                <v n="IsFastStateDiagram">false</v>
                <l n="StereoTypeProfile" t="ArrayList" />
                <v n="RelationRoleID">2</v>
                <d n="PositionSerialization" t="Hashtable" ckt="Int64" cvt="Guid">
                  <v>1</v>
                  <v>7c75664d-1068-4216-bb68-0988792aad57</v>
                  <v>2</v>
                  <v>bfa2c643-82d0-4726-86c3-cf47d8f6028d</v>
                  <v>3</v>
                  <v>27943c4e-de77-4fd5-905f-c6e7bc0b05c3</v>
                  <v>4</v>
                  <v>27943c4e-de77-4fd5-905f-c6e7bc0b05c3</v>
                  <v>5</v>
                  <v>c7c0963f-5ae5-4645-98f1-f8436613952a</v>
                  <v>6</v>
                  <v>bd255ad8-73c8-46b4-a11e-4c77f6294430</v>
                </d>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="ArrowTypes">{812dac4c-85cd-4336-bb2f-f967774b251e}</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Docked">{7586ffd4-4b2d-494c-aff5-a40d31dac111}</Type>
              <Type n="Double">System.Double</Type>
              <Type n="EditorRestrictions">{1ca7a370-7213-48b2-9df6-3ac7e85f0c68}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Hashtable">System.Collections.Hashtable</Type>
              <Type n="HistoryTypes">{3534dff0-3cd3-4ab6-8e74-b81ff8613005}</Type>
              <Type n="ImplicitStartStateTypes">{159536e2-c3a1-4501-a760-7b5009964f41}</Type>
              <Type n="Int16">System.Int16</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="RelationTypes">{f5146002-a332-47c0-9d9a-7997d539e6a9}</Type>
              <Type n="String">System.String</Type>
              <Type n="UInt32">System.UInt32</Type>
              <Type n="UMLAnchorPoint">{610ad96d-085d-4ced-95e0-831f42edefc2}</Type>
              <Type n="UMLDiagramProperties">{71bc64fb-98e8-4f9a-b2ec-0da66cfaa0a0}</Type>
              <Type n="UMLRelation">{66eb2f12-934d-4c0a-8710-d6fec8d1ff48}</Type>
              <Type n="UMLRelationVisualisation">{79af0d10-00d2-4abe-9c91-6b4e07d4aa1d}</Type>
              <Type n="UMLStateChart">{9b0dd937-6691-44b8-b0c0-27601a5e098a}</Type>
              <Type n="UMLStateChartDiagramElementVisualisationDot">{573ce27a-c0d4-453b-8ffd-6d125a13ad66}</Type>
              <Type n="UMLStateChartElement">{a9cbb7e7-7aa8-4772-a0f9-efee80bd48b2}</Type>
              <Type n="UMLStateChartElementVisualisation">{861a8beb-602e-4017-bf45-a602984c46fe}</Type>
              <Type n="UMLStateChartPseudoElement">{3569ebb7-c8a3-4ab4-b440-d179b9e0fe9b}</Type>
              <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
            </TypeList>
          </XmlArchive>
        </StateChart>
      </Implementation>
    </Method>
    <Method Name="TestCase2A" Id="{08302e5c-315f-491e-adf5-28ac987840cc}">
      <Declaration><![CDATA[METHOD TestCase2A
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('TestCase2A');

AssertTrue(TRUE, 'Condition is not true');

TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
    <Method Name="TestCase2B" Id="{d124f6c2-5ec2-4271-8a1e-818da4d1bf79}">
      <Declaration><![CDATA[METHOD TestCase2B
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('TestCase2B');

AssertTrue(TRUE, 'Condition is not true');
AssertTrue(TRUE, 'Condition is not true');

TEST_FINISHED();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>