<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TESTS" Id="{2f8fcc6e-c36b-40b5-a0ea-8b06b18e1a90}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TESTS
VAR
    fbTestSuite1Instance1 : FB_TestSuite1;
    fbTestSuite2Instance1 : FB_TestSuite2;
    fbTestSuite2Instance2 : FB_TestSuite2;
    fbTestSuiteGroup : FB_TestSuiteGroup;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>